version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  stereum-init:
    image: stereum/init:buster
    restart: "no"
    volumes:
      - ./data/grafana:/mnt/grafana
      - ./data/prometheus:/mnt/prometheus
      - ./data/consensys/teku:/mnt/teku
      - ./config/teku/beacon.yaml:/mnt/config
      - ./launchpad:/mnt/launchpad
    <<: *logging

  geth:
    image: ethereum/client-go:${GETH_DOCKER_TAG}
    restart: always
    hostname: geth
    command: --goerli --http --http.port=8545 --http.addr=0.0.0.0 --http.vhosts="*" --allow-insecure-unlock --http.api="db,eth,net,web3,personal"
    stop_grace_period: 5m
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - ${BEACON_API_IP}:8545:8545
    networks:
      default:
      stereum-admin:
    volumes:
      - ./data/geth:/root/.ethereum
    <<: *logging

  beacon:
    image: consensys/teku:${TEKU_DOCKER_TAG}
    restart: always
    hostname: beacon-chain
    user: "1001"
    depends_on:
      - stereum-init
      - geth
    command: --config-file=/config/beacon.yaml
    environment:
      - "JAVA_OPTS=-Xmx3g"
    ports:
      - 9001:9001
      - ${BEACON_API_IP}:5051:5051
    networks:
      default:
      stereum-admin:
    volumes:
      - ./data/consensys/teku:/opt/teku/data
      - ./config/teku/beacon.yaml:/config/beacon.yaml:ro
      - ./launchpad:/launchpad
    <<: *logging

  prometheus:
    image: prom/prometheus:${PROMETHEUS_DOCKER_TAG}
    user: "1001"
    restart: on-failure
    hostname: prometheus
    depends_on:
      - stereum-init
    command: --storage.tsdb.retention.time=7d --config.file=/etc/prometheus/prometheus.yml
    ports:
      - ${BEACON_API_IP}:9090:9090
    volumes:
      - ./config/prometheus/prometheus-t.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    <<: *logging

  grafana:
    image: grafana/grafana:${GRAFANA_DOCKER_TAG}
    restart: on-failure
    hostname: grafana
    user: "1001"
    depends_on:
      - stereum-init
      - prometheus
    ports:
      - ${BEACON_API_IP}:3000:3000
    volumes:
      - ./config/grafana/provisioning-t:/etc/grafana/provisioning:ro
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8082/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000    
    <<: *logging

  renderer:
    image: grafana/grafana-image-renderer:${GRAFANA_IMAGE_RENDERER_TAG}
    user: "1001"
    restart: on-failure
    hostname: renderer
    environment:
      ENABLE_METRICS: 'true'
      HTTP_PORT: 8082
    <<: *logging

  node-exporter:
    image: prom/node-exporter:${PROMETHEUS_NODE_EXPORTER_DOCKER_TAG}
    user: "1001"
    hostname: node-exporter
    <<: *logging

networks:
  stereum-admin:
    internal: true
  default:

# EOF
